service: nextbus
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

  region: eu-north-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  busstop:
    handler: bin/busstop
    events:
      - http:
          path: busstop
          method: get
